[package]
name = "crumbs"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
bytes = "1"
blake3 = "1"
charabia = "0.9.8"
clap = { version = "4", features = ["derive", "env"] }
confique = { version = "0.4.0", features = ["toml", "json5", "yaml"] }
cupido = "0.3.5"
dirs = "6"
eyre = "0.6"
futures = "0.3"
http = "1"
indicatif = { version = "0.18.3", features = ["rayon", "improved_unicode"] }
libsql = "0.9.29"
pin-project-lite = "0.2"
reqwest = { version = "0.13.1", features = ["json", "stream"] }
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syntastica-queries = "0.6.1"
syntastica = "0.6.1"
syntastica-parsers = { version = "0.6.1", features = ["most"] }
syntastica-themes = "0.6.1"
dark-light = "2"
text-chunking = { version = "0.2.1", registry = "forgejo" }
tiktoken-rs = "0.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
tokio-util = "0.7"
toml_edit = { version = "0.22", features = ["serde"] }
tokenizers = { version = "0.22.1", default-features = false, features = ["esaxx_fast", "http", "onig"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tree-sitter = "0.25"
uuid = { version = "1", features = ["v7"] }

[dev-dependencies]
tempfile = "3"
