[settings]
experimental = true

[tools]
"cargo:samply" = "latest"
hk = "latest"
pkl = "latest"
rust = "1.92.0"

[env]
_.file = ".env.json"
EMBEDDER_API_KEY = "{{ env.DEEPINFRA_API_KEY }}"

[tasks.test]
run = "cargo test --all"
